esphome:
  name: bb-node00

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifissid
  password: !secret wifipass
  fast_connect: true
  manual_ip:
    static_ip: 172.16.99.50
    gateway: 172.16.99.1
    subnet: 255.255.255.0
    dns1: 172.16.10.2
    dns2: 172.16.10.5

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bb-Node00 Fallback Hotspot"
    password: "m38y6JhB9Wde"

captive_portal:

sensor:
  - platform: dht
    pin: D1
    temperature:
      name: "Guest Room Temperature"
    humidity:
      name: "Guest Room Humidity"
    update_interval: 10s
    model: DHT11

mqtt:
  broker: !secret mqttbroker
  username: !secret mqttuser
  password: !secret mqttpassword
  client_id: bb-esp-gr
  on_message:
    - topic: home/ota_mode
      payload: 'ON'
      then:
        - deep_sleep.prevent: deep_sleep_1
    - topic: home/sleep_mode
      payload: 'ON'
      then:
        - deep_sleep.enter: deep_sleep_1

deep_sleep:
  run_duration: 30s
  sleep_duration: 10min
  id: deep_sleep_1
