esphome:
  name: bb-node03

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: "The_Babies2.4"
  password: "pipocacomnutella"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bb-Node01 Fallback Hotspot"
    password: "m38y6JhB9Wde"

captive_portal:

sensor:
  - platform: dht
    pin: 25
    temperature:
      name: "Kitchen Room Temperature"
    humidity:
      name: "Kitchen Room Humidity"
    update_interval: 60s    
    model: DHT11
