esphome:
  name: sonoff-heater

esp8266:
  board: esp8285

wifi:
  ssid: The_Babies2.4
  password: pipocacomnutella
  fast_connect: true
  manual_ip:
    static_ip: 172.16.10.55
    gateway: 172.16.10.1
    subnet: 255.255.255.0
    dns1: 172.16.10.16
    dns2: 172.16.10.5
api:

logger:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Heater Button"
    on_press:
      - switch.toggle: relay
  - platform: gpio
    name: "Heater Ext Button"
    pin: GPIO04
    on_state:
      - switch.toggle: relay
switch:
  - platform: gpio
    name: "Heater Sonoff"
    pin: GPIO12
    id: relay
    restore_mode: RESTORE_DEFAULT_ON
status_led:
  pin:
    number: GPIO13
    inverted: yes
