esphome:
  name: sonoff-lights1

esp8266:
  board: esp8285

wifi:
  ssid: The_Babies2.4
  password: pipocacomnutella

api:

logger:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Sonoff Basic Button"
    on_press:
      - switch.toggle: relay
  - platform: gpio
    name: "Sonoff Ext Button"
    pin: GPIO04
    id: switch_1
    on_state:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Sonoff Basic Relay"
    pin: GPIO12
    id: relay
    restore_mode: RESTORE_DEFAULT_OFF

status_led:
  pin:
    number: GPIO13
    inverted: yes
