esphome:
  name: sonoff-heater

esp8266:
  board: esp8285

logger:

api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifissid
  password: !secret wifipass
  fast_connect: true
  manual_ip:
    static_ip: 172.16.99.55
    gateway: 172.16.99.1
    subnet: 255.255.255.0
    dns1: 172.16.10.2
    dns2: 172.16.10.5

captive_portal:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Heater Button"
    on_press:
      - switch.toggle: relay
  - platform: gpio
    name: "Heater Ext Button"
    pin: GPIO04
    on_state:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Heater Sonoff"
    pin: GPIO12
    id: relay
    restore_mode: RESTORE_DEFAULT_ON

status_led:
  pin:
    number: GPIO13
    inverted: yes

mqtt:
  broker: !secret mqttbroker
  username: !secret mqttuser
  password: !secret mqttpassword
  client_id: bb-sonoff-heater
